### ISSUE TITLE
compile hottub error 

### ISSUE THREAD

**Issue by Ddnirvana** [dsrg-uoft/hottub#2]
Hi, guys,

 I am interested about the project and want to try it. However, I meet some compile errors.

I use `bash ./configure` to configure the environment.
<pre>
====================================================
A new configuration has been successfully created in
/home/dd/devlop/java/jvm/hottub/hottub/build/linux-x86_64-normal-server-release
using default settings.

Configuration summary:
* Debug level:    release
* JDK variant:    normal
* JVM variants:   server
* OpenJDK target: OS: linux, CPU architecture: x86, address length: 64

Tools summary:
* Boot JDK:       java version "1.7.0_181" OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-0ubuntu0.1) OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)  (at /usr/lib/jvm/java-7-openjdk-amd64)
* C Compiler:     gcc-4.8 (Ubuntu 4.8.5-4ubuntu8~14.04.2) version 4.8.5 (at /usr/bin/gcc-4.8)
* C++ Compiler:   g++-4.8 (Ubuntu 4.8.5-4ubuntu8~14.04.2) version 4.8.5 (at /usr/bin/g++-4.8)

Build performance summary:
* Cores to use:   7
* Memory limit:   15927 MB
* ccache status:  installed and in use

WARNING: The result of this configuration has overridden an older
configuration. You *should* run 'make clean' to make sure you get a
proper build. Failure to do so might result in strange build problems.
</pre>
The configure summary is shown in the above.

Then `./make_hottube.sh dd_test fastdebug`, which will cause the following error messages.
<pre>
Compiling /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/prims/jniCheck.cpp
Compiling /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/prims/jniFastGetField.cpp
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp: In static member function ‘static void InstanceKlass::zero_init(Klass*, Thread*)’:
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:3995:93: error: cannot pass objects of non-trivially-copyable type ‘class oop’ through ‘...’
       ik->name()->as_C_string(), ik->reinit_safe(), ik->is_initialized(), ik->class_loader());
                                                                                             ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp: In member function ‘bool InstanceKlass::should_record()’:
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:4163:126: error: too many arguments for format [-Werror=format-extra-args]
       tty->print_cr("[HotTub][warn][InstanceKlass::should_record] class %p with no class loader data or name", p2i(this), buf);
                                                                                                                              ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp: In static member function ‘static void InstanceKlass::clinit_replay(Thread*)’:
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:4198:134: error: conversion from ‘oop’ to ‘bool’ is ambiguous
         name_c_str, ik->reinit_safe(), ik->class_loader(), ik->class_loader() ? ik->class_loader()->klass()->name()->as_C_string() : "null");
                                                                                                                                      ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:4198:134: note: candidates are:
In file included from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/utilities/top.hpp:28:0,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/iterator.hpp:31,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/genOopClosures.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/klass.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/runtime/handles.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/universe.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/code/oopRecorder.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/asm/codeBuffer.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/asm/assembler.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/precompiled/precompiled.hpp:29,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:25:
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:145:3: note: oop::operator oop*() const
   operator oop* () const              { return (oop *)obj(); }
   ^
In file included from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/utilities/top.hpp:28:0,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/iterator.hpp:31,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/genOopClosures.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/klass.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/runtime/handles.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/memory/universe.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/code/oopRecorder.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/asm/codeBuffer.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/asm/assembler.hpp:28,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/precompiled/precompiled.hpp:29,
                 from /home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/instanceKlass.cpp:25:
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:136:3: note: oop::operator JavaThread*() const
   operator JavaThread* () const       { return (JavaThread*)obj(); }
   ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:134:3: note: oop::operator jobject() const
   operator jobject () const           { return (jobject)obj(); }
   ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:131:3: note: oop::operator address() const
   operator address   () const         { return (address)obj(); }
   ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:129:3: note: oop::operator markOop() const
   operator markOop () const           { return markOop(obj()); }
   ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:128:3: note: oop::operator PromotedObject*() const
   operator PromotedObject* () const   { return (PromotedObject*)obj(); }
   ^
/home/dd/devlop/java/jvm/hottub/hottub/hotspot/src/share/vm/oops/oopsHierarchy.hpp:127:3: note: oop::operator intptr_t*() const
</pre>

I have tried to build openjdk-8 in my machine and succeeded... So from my view, I think the compiling environment(gcc, g++, and make) should be OK. But the error message seems about the compiler version problem? I am not sure....

Any advices are welcomed!! Thanks very much!

**Comment by davidlion** [comment]
Your environment looks fine (I double checked gcc-4.8 as well). The errors were hottub-added code that works in release, but not any debug version (this is why openjdk built fine for you).

The issue has to do with how the "oop" type works. In release it is just a pointer, but in debug versions it is a wrapper class. These errors directly used an oop as if it were a pointer.

I pushed the fixes in da9258fcd77d1dde640e03b8dec4d8d1f019cd82. Let me know if you still have issues and thanks for letting us know.

**Comment by Ddnirvana** [comment]
Yes! The da9258f perfectly solve the compile problem! Now I can compile hottub and try to see some profile results! 

Thank you a lot! @davidlion
